### ISSUE TITLE
A flag to return text clipboard by default if requested board not available

### ISSUE THREAD

**Issue by amardeep** [chbrown/macos-pasteboard#6]
I would like to propose a feature request to add a flag to return text clipboard if requested board is not available.

Right now i am using something like (pbv public.html 2>/dev/null | pbv) | pandoc ..., but it would be nice to have a flag with that behaviour.

**Comment by chbrown** [comment]
I expect you mean `(pbv public.html 2>/dev/null || pbv) | pandoc ...`? In bash, when using a `||` rather than a `|`, `(... | pbv) | pandoc ...` would be just like calling `pbv | pandoc ...`, since `pbv` does nothing with `/dev/stdin`.

It's an interesting idea / good suggestion! Also, feeling surprised / stoked that other people actually find this tool helpful 😄 

Currently, `pbv` takes either zero or one arguments, and in the zero case, behaves exactly as if it was called with one argument, like `pbv public.utf8-plain-text`. That's the default since that's my most common use case and AFAICT it's also the same as calling `pbpaste` with no arguments.

The way I'm thinking I'd implement this would be to require _all_ acceptable formats if _any_ format is given — meaning that the zero-argument usage remains a special case, and providing one or more arguments operates similar to how one-argument usage works now. My thinking is that if `pbv dataType1` silently reverted to plain text if `dataType1` was unavailable, it'd be impossible (or at least painful) to detect a failure to obtain some desired data type(s), which might be a hard requirement (e.g., piping `pbv` output into `xmlstarlet`). This would still support your use-case, but with a slightly different, more verbose syntax — thinking something like `pbv public.html public.utf8-plain-text | pandoc ...`. Or come to think of it — maybe it's not all that different — just that this way you have to explicitly supply the same argument to `pbv` that it otherwise uses as the default.

Lemme work on it; I'll come back and close this if/when I push a suitable implementation 😉

**Comment by amardeep** [comment]
You are right about the missing braces.

Your solution works perfectly - in that case there is no need for an
argument for default text.

**Comment by chbrown** [comment]
Okay, you should now (after [re-installing](https://github.com/chbrown/macos-pasteboard#install)) be able to use that alternative I proposed above, specifically:
```sh
pbv public.html public.utf8-plain-text | pandoc ...
```
Enjoy! ⚡
